### ISSUE TITLE
The idf.py file missing in the root

### ISSUE THREAD

**Issue by nlv-hack** [m5stack/M5Dial-UserDemo#4]
According to the README.MD file to build the project one need to 

```bash
git clone https://github.com/m5stack/M5Dial-UserDemo.git
cd M5Dial-UserDemo
idf.py build
```

But the `idf.py` file isnt in the repo. I guess it somewhat relates to #2

**Comment by nlv-hack** [comment]
Added brief installation steps here in [PR](https://github.com/m5stack/M5Dial-UserDemo/pull/5)

**Comment by Forairaaaaa** [comment]
Thanks!
