### ISSUE TITLE
Encoder Ring Not Working After Flashing

### ISSUE THREAD

**Issue by sayzard** [m5stack/M5Dial-UserDemo#8]
I recently purchased an M5Dial. 
Everything was working fine until I downloaded the firmware from GitHub, built it, and flashed it onto the device. After the flashing process, the encoder ring stopped responding. The click functionality is still operational, allowing access to the LCD TEST menu, but the rotation of the encoder does not trigger any response.

Could anyone provide guidance on whether there is a specific configuration or setting adjustment needed during the build process to get the encoder ring working again? Any assistance would be greatly appreciated.

Thank you.

**Comment by moisesfa** [comment]
The encoder works if you comment these lines in the main file.
I still don't know why, but it works.

```
    // if (!hal.encoder.btn.read())
    // {   
    //     uint16_t time_count = 0;
    //     while (!hal.encoder.btn.read())
    //     {
    //         delay(10);
    //         time_count++;
    //         if ((time_count * 10) > 1000)
    //         {
    //             factory_test_mode = true;
    //             break;
    //         }
    //     }
    // }
```
Regards

**Comment by Forairaaaaa** [comment]
Hi, it's a bug comes with encoder library, will be fixed in the future

**Comment by Forairaaaaa** [comment]
It should be fix now

**Comment by sayzard** [comment]
Thanks for fixing the issue. It works great now!
